- hosts: batch2

  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes
      tags: nginx

    - name: Create a user 'johnd' with a home directory
      ansible.builtin.user:
        name: johnd
      become: yes
      tags: nginx 	

    - name: update cache
      ansible.builtin.apt:
        update_cache: true
      become: yes
      tags: updatecache
