- hosts: batch2
  become: yes
  
  vars:
    nginx_port: 8090
    root_dir: /Users/dmitrijlarionov/kubernetes-certification-guide/lab-setup/mac-silicon/files/
  
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
   
    - name: start nginx
      service: 
        name: nginx
        state: started
        enabled: yes

    - name: copy index.html
      ansible.builtin.template:
        src: "{{root_dir}}index.html"
        dest: /usr/share/nginx/html/index.html

    - name: template nginx.conf
      ansible.builtin.template:
        src: "{{root_dir}}nginx.conf"
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
 
